### ISSUE TITLE
Use `bevy` subcrates, ie `bevy_ecs`

### ISSUE THREAD

**Issue by mrchantey** [projectharmonia/bevy_replicon#217]
This crate looks awesome and exactly what I need, only some of the targets for my project are tiny microcontrollers so im being pretty conservative regarding dependencies.

Would you be open to using `bevy_ecs`, `bevy_app`, `bevy_reflect` etc instead of the kitchen sink `bevy` crate? This should also speed up compile times and make `rust-analyzer` quicker.

**Comment by Shatur** [comment]
We trying to follow [Bevy guidelines](https://bevyengine.org/learn/quick-start/plugin-development) and it looks like they mention `default-features = false` and that's what we're doing.

Looks like other popular crates do the same:
- [leafwing-input-manager](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/main/Cargo.toml).
- [bevy_xpbd](https://github.com/Jondolf/bevy_xpbd/blob/main/crates/bevy_xpbd_3d/Cargo.toml).
- [bevy_egui](https://github.com/mvlabat/bevy_egui/blob/main/Cargo.toml)

I even remember that `leafwing-input-manager` changed to using `bevy_*` crates, but after some time changed it back. Don't remember the reason for the change, but I pretty sure that `@alice-i-cecily` had a one...

For now we require `bevy_scene` enabled (it enables others, like `bevy_ecs` and `bevy_reflect`), but it's because of [this](https://github.com/projectharmonia/bevy_replicon/blob/master/src/scene.rs) module. So we could make this module optional if you want so.

**Comment by mrchantey** [comment]
Ok yeah thats good to know. I saw `bevy_window` is included even with `default-features = false` and assumed that pulls in `winit` which blocks compilation for my target. But yeah i was mistaken, thats upstream from `winit`, thanks for the explanation ill see if i can do the same for my crate.
